bucket_name = "bucket-frontend-devops-test"
bucket_tag_environment = "test"
bucket_tag_name = "Bucket Test"

cluster_name = "test"

ecs_product_name = "products-service-test"
load_balancer_name = "load_balancer_access_test"
products_sg_name = "products-sg-test"
product_family_ecs_task_definition = "products-service-test"
product_cpu = "256"
product_memory = "512"
products_alb_name = "products-alb-test"
products_target_group_lb_name  = "products-target-group-test"
product_container_name = "products-service-test"

### ORDER ###
ecs_order_name = "orders-service-test"
order_sg_name = "orders-sg-test"
order_family_ecs_task_definition = "orders-service-test"
order_cpu = "256"
order_memory = "512"
orders_alb_name = "orders-alb-testtt"
orders_target_group_lb_name  = "orders-target-group"
order_container_name = "orders-service-test"

### SHIPPING ###
ecs_shipping_name = "shipping-service-test"
shipping_sg_name = "shipping-sg-test"
shipping_family_ecs_task_definition = "shipping-service-test"
shipping_cpu = "256"
shipping_memory = "512"
shipping_alb_name = "shipping-alb-testtt"
shipping_target_group_lb_name  = "shipping-target-group"
shipping_container_name = "shipping-service-test"

### PAYMENTS ###
ecs_payments_name = "payments-service-test"
payment_sg_name = "payments-sg-test"
payment_family_ecs_task_definition = "payments-service-test"
payment_cpu = "256"
payment_memory = "512"
payment_alb_name = "payments-alb-testtt"
payment_target_group_lb_name  = "payments-target-group"
payment_container_name = "payments-service-test"