bucket_name = "bucket-testttt1"
bucket_tag_environment = "test"
bucket_tag_name = "Bucket Test"

cluster_name = "test"
ecs_product_name = "products-test"
load_balancer_name = "load_balancer_acess_test"
products_sg_name = "products-sg-test"
product_family_ecs_task_definition = "product-test"
product_cpu = "256"
product_memory = "512"
products_alb_name = "products-alb-test"
products_target_group_lb_name  = "products-target-group-test"

### ORDER ###
ecs_order_name = "orders-test"
order_sg_name = "order-sg-test"
order_family_ecs_task_definition = "order-test"
order_cpu = "256"
order_memory = "512"
orders_alb_name = "products-alb-testtt"
orders_target_group_lb_name  = "orders-target-group"

### SHIPPING ###
ecs_shipping_name = "shipping-test"
shipping_sg_name = "shipping-sg-test"
shipping_family_ecs_task_definition = "shipping-test"
shipping_cpu = "256"
shipping_memory = "512"
shipping_alb_name = "shipping-alb-testtt"
shipping_target_group_lb_name  = "shipping-target-group"

### PAYMENTS ###
ecs_payments_name = "payment-test"
payment_sg_name = "payment-sg-test"
payment_family_ecs_task_definition = "payment-test"
payment_cpu = "256"
payment_memory = "512"
payment_alb_name = "payment-alb-testtt"
payment_target_group_lb_name  = "payment-target-group"